### ISSUE TITLE
Red Scroll Bars

### ISSUE THREAD

**Issue by MrNightwood** [tokeidlom/STA-LCARS-UI#1]
Scroll bars appear to be the same square, purplish-red color from the base system rather than rounded off blue from the LCARS UI.

Current: 
![image](https://github.com/user-attachments/assets/2833bf5c-e672-4455-b49e-49f04ec74dbf)
Expected: 
![image](https://github.com/user-attachments/assets/5ab0cb6b-939b-459f-b97b-82f47b0c8a72)

**Comment by tokeidlom** [comment]
Just out of interest, where did you screenshot the blue bars? I've rolled back the CSS in the module to Fabulist version and the red bars persist (although the CSS clearly says scrollbars should be blue). I'm wondering if something in the STA system updates has changed this. Just trying to zero in on it by finding out what combo of versions it was last working with.

**Comment by tokeidlom** [comment]
Ok, looks like it was a change in foundry V12 that caused it.

**Comment by MrNightwood** [comment]
Not that you still need it to narrow down the issue, but the screenshot was just cropped from the cover image of the module.

**Comment by tokeidlom** [comment]
If you can grab the update and test again, should now be working, seems chromium browsers depreciated the function that was using!

**Comment by MrNightwood** [comment]
The color has been corrected, the only thing still remaining is that the scroll bars in the original LCARS UI were rounded at the ends and not capped by arrows. We're in nitpick territory now though, the mismatched color was certainly the biggest issue.

Image for reference (Current on left, original LCARS module on right):
![image](https://github.com/user-attachments/assets/2092d3e5-4945-459b-a551-0dd0305e1142)

**Comment by tokeidlom** [comment]
I think I'm going to say thats close enough for me :)
Thanks for reporting!
